### ISSUE TITLE
[addrelease] TypeError: super() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by arthurlutz** [musicbrainz/picard-plugins#198]
On picard 1.4.2 the install plugin via the options installs an older version of addrelease which uses API 1.0. No contextual menu. So I tried to download the most recent version and integrate it in the zip. I then get : 

```
E: 10:55:03 Plugin 'addrelease' : Traceback (most recent call last):
  File "/usr/lib/picard/picard/plugin.py", line 299, in load_plugin
    plugin_module = imp.load_module(_PLUGIN_MODULE_PREFIX + name, *info)
  File "/home/arthur/.config/MusicBrainz/Picard/plugins/addrelease.py", line 243, in <module>
    register_cluster_action(AddClusterAsRelease())
  File "/home/arthur/.config/MusicBrainz/Picard/plugins/addrelease.py", line 120, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)

E: 10:55:03 Plugin 'addrelease' : Traceback (most recent call last):
  File "/usr/lib/picard/picard/plugin.py", line 301, in load_plugin
    plugin_module = importer.load_module(_PLUGIN_MODULE_PREFIX + name)
  File "/home/arthur/.config/MusicBrainz/Picard/plugins/addrelease.zip/addrelease.py", line 243, in <module>
  File "/home/arthur/.config/MusicBrainz/Picard/plugins/addrelease.zip/addrelease.py", line 120, in __init__
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by arthurlutz** [comment]
Upgraded to picard 2.1 from PPA, but the menu still doesn't appear. version 0.7.2 and 0.7.3 tested without success.

**Comment by phw** [comment]
The menu entry is in the context menu of a cluster inside the "Plugins" submenu:

![grafik](https://user-images.githubusercontent.com/29852/53812532-fbc3d580-3f5b-11e9-9d49-96356dc4e15d.png)

The important part is that you need to cluster your files first.
